// AUTO-GENERATED BY UpdatePartyVersion.ps1 - DO NOT MODIFY
#if UNITY_STANDALONE || UNITY_IOS || UNITY_ANDROID || UNITY_GAMECORE || MICROSOFT_GAME_CORE || UNITY_STANDALONE_LINUX || UNITY_EDITOR_LINUX
namespace PlayFab.Party
{
    internal static class Version
    {
        public static readonly string PartyNativeVersion = "{1.7.6}152418";
        public static readonly string PartyUnityVersion = "{1.7.6.0-main.0}152418";
    }
}
#endif
